Repository DeveloperAcademy-POSTECH/2025-C3-A15-AGZ, pull requests merged in 2025-06, with the labels that each got.

#5 🎨 Design: #4 TeamMainView 구현, ✨Feat: DynamicValue 함수 및 text spacing 관련 커스텀 수정자 구현
  CheerLot/CheerLot/Assets.xcassets/Colorchip/Gray/gray01.colorset/Contents.json
  CheerLot/CheerLot/Resources/Common/DesignSystem/BasicTextStyle.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/DynamicLayout.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/RoundedCorner.swift
  CheerLot/CheerLot/Resources/Common/Enum/MemberListMenuSegment.swift
  CheerLot/CheerLot/Resources/Common/Enum/Theme.swift
  CheerLot/CheerLot/Resources/Extension/Font+.swift
  CheerLot/CheerLot/Resources/Extension/View+.swift
  CheerLot/CheerLot/Resources/Models/Player.swift
  CheerLot/CheerLot/Resources/Models/Team.swift
  CheerLot/CheerLot/Resources/Presentation/Main/MemberListMenuSegmentControl.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRosterView.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberCell.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/c5.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/ttt.swift
  CheerLot/CheerLot/Resources/Presentation/TeamMember/c20.swift
  CheerLot/CheerLot/Resources/Presentation/TeamMember/c6.swift
Labels: 🎨 Design, ✨ Feature

#9 🎨 Feat: #6 StartingMemeberListView 및 인터렉션 구현
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/Contents.json
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/ss_mainTopBG.imageset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/ss_mainTopBG.imageset/MainTopBG.pdf
  CheerLot/CheerLot/Assets.xcassets/caution.imageset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/caution.imageset/caution.svg
  CheerLot/CheerLot/Assets.xcassets/changeIcon.imageset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/changeIcon.imageset/aaa.svg
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuCell.swift
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Resources/Common/Components/CustomToastMessageView.swift
  CheerLot/CheerLot/Resources/Common/Components/c8.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/BasicTextStyle.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/DynamicLayout.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/RoundedCornerShape.swift
  CheerLot/CheerLot/Resources/Common/Enum/MemberListMenuSegment.swift
  CheerLot/CheerLot/Resources/Common/Navigation/MainRoute.swift
  CheerLot/CheerLot/Resources/Common/Navigation/NavigationRouter.swift
  CheerLot/CheerLot/Resources/Models/Player.swift
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/c2.swift
  CheerLot/CheerLot/Resources/Presentation/Main/MemberListMenuSegmentControl.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRosterView.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberCell.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/sss.swift
Labels: 🎨 Design, ✨ Feature

#14 🍀 Chore: #10 Watch OS 프로젝트 초기 세팅
  CheerLot/CheerLot.xcodeproj/project.pbxproj
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Resources/Common/DesignSystem/DynamicLayout.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Contents.json
  CheerLot/WatchCheerLot Watch App/Preview Content/Preview Assets.xcassets/Contents.json
  CheerLot/WatchCheerLot Watch App/Resources/Common/DesignSystem/BasicTextStyle.swift
  CheerLot/WatchCheerLot Watch App/Resources/Common/DesignSystem/WatchDynamicLayout.swift
  CheerLot/WatchCheerLot Watch App/Resources/Extension/Font+.swift
  CheerLot/WatchCheerLot Watch App/Resources/Extension/View+.swift
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Freshman.ttf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Black.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Bold.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-ExtraBold.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-ExtraLight.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Light.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Medium.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Regular.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-SemiBold.otf
  CheerLot/WatchCheerLot Watch App/Sources/Fonts/Pretendard-Thin.otf
  CheerLot/WatchCheerLot Watch App/WatchCheerLotApp.swift
  CheerLot/WatchCheerLot-Watch-App-Info.plist
Labels: 📂 Chore

#24 ✨ Feat: #22 선수 교체 구현
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
Labels: ✨ Feature

#33 ✨ Feat: #23 watchOS에서 StartingMemberListView 구현 및 Watch Connectivity 구현
  CheerLot/CheerLot.xcodeproj/project.pbxproj
  CheerLot/CheerLot/Assets.xcassets/AppIcon.appiconset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/AppIcon.appiconset/icon 1.png
  CheerLot/CheerLot/Assets.xcassets/AppIcon.appiconset/icon 2.png
  CheerLot/CheerLot/Assets.xcassets/AppIcon.appiconset/icon.png
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/SS/Contents.json
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/SS/ss_changeTopBG.imageset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/SS/ss_changeTopBG.imageset/ss_changeTopBG.pdf
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/SS/ss_mainTopBG.imageset/Contents.json
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/SS/ss_mainTopBG.imageset/ss_mainTopBG.pdf
  CheerLot/CheerLot/Assets.xcassets/TeamTopBG/ss_mainTopBG.imageset/MainTopBG.pdf
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Resources/Common/Enum/Theme.swift
  CheerLot/CheerLot/Resources/Models/Response/LineupResponse.swift
  CheerLot/CheerLot/Resources/Models/SwiftData/CheerSong.swift
  CheerLot/CheerLot/Resources/Models/SwiftData/Player.swift
  CheerLot/CheerLot/Resources/Models/SwiftData/Team.swift
  CheerLot/CheerLot/Resources/Models/WatchDto/PlayerWatchDto.swift
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/AppIcon.appiconset/icon.png
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Etc/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Etc/edit.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/gray01.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/gray02.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/gray03.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/gray04.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/Gray/gray05.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/SS/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/SS/ss_button.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/SS/ss_player.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/Colorchip/SS/ss_primary.colorset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/ss_listBG.imageset/Contents.json
  CheerLot/WatchCheerLot Watch App/Assets.xcassets/ss_listBG.imageset/ss_listBG.pdf
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/Lyrics/LyricsView.swift
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/Start/MissingPlayerListView.swift
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/Start/StartView.swift
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/WatchCheerLot Watch App/Resources/Presentation/StartingMember/StartingMemberListViewModel.swift
Labels: 🎨 Design, ✨ Feature

#37 ♻️ Refactor: #36 CheerSongView UI 수정 및 CustomSeekBar 구현
  CheerLot/CheerLot/Resources/Common/Components/CustomSeekBar.swift
  CheerLot/CheerLot/Resources/Presentation/CheerSong/CheerSongView.swift
  CheerLot/CheerLot/Resources/Presentation/CheerSong/CheerSongViewModel.swift
Labels: ✨ Feature, ♻️ Refactor

#42 ♻️ Refactor: #39 전체 선수 데이터 필터, 정렬
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/TeamMember/TeamMemberListView.swift
Labels: ♻️ Refactor

#53 ✨ Feat: #49 TeamSelectSheetView 구현
  CheerLot/CheerLot/Resources/Common/Components/TeamSelectSeetView.swift
  CheerLot/CheerLot/Resources/Common/Components/TeamSelectSheetView.swift
  CheerLot/CheerLot/Resources/Common/Enum/Theme.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
Labels: ✨ Feature, 🔨 Fix

#61 ♻️ Refactor: #60 Player 수정, id를 이용하여 선수 식별
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Resources/Models/SwiftData/Player.swift
  CheerLot/CheerLot/Resources/Models/WatchDto/PlayerWatchDto.swift
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/TeamMember/TeamMemberListView.swift
  CheerLot/CheerLot/Sources/Data/DataMigrationService.swift
  CheerLot/CheerLot/Sources/Data/TeamsData.swift
  CheerLot/CheerLot/Sources/Data/teams.json
Labels: ♻️ Refactor
