Repository DeveloperAcademy-POSTECH/2025-C3-A15-AGZ, pull requests merged in 2025-09, with the labels that each got.

#95 ♻️ Refactor: #93 NavigationRouter 리팩토링
  CheerLot/CheerLot/App/CheerLotApp.swift
  CheerLot/CheerLot/Common/Enum/AppInfoMenu.swift
  CheerLot/CheerLot/Common/Protocol/NavigationRoutable.swift
  CheerLot/CheerLot/Common/Protocol/c10.swift
  CheerLot/CheerLot/Common/UIComponents/AppInfo/AppInfoTextPageView.swift
  CheerLot/CheerLot/Common/UIComponents/Custom/CustomNavigationBar.swift
  CheerLot/CheerLot/Common/UIComponents/Song/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Core/DIContainer/DIContainer.swift
  CheerLot/CheerLot/Core/Navigation/NavigationDestination.swift
  CheerLot/CheerLot/Core/Navigation/NavigationRouter.swift
  CheerLot/CheerLot/Core/Navigation/NavigationRoutingView.swift
  CheerLot/CheerLot/Presentation/AppFlow/AppFlowViewModel.swift
  CheerLot/CheerLot/Presentation/AppFlow/Splash/SplashView.swift
  CheerLot/CheerLot/Presentation/AppInfo/Views/AboutMakerView.swift
  CheerLot/CheerLot/Presentation/AppInfo/Views/MainAppInfoView.swift
  CheerLot/CheerLot/Presentation/Change/Views/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Presentation/Main/Views/StartingMemberListView.swift
  CheerLot/CheerLot/Presentation/Main/Views/TeamRoasterView.swift
  CheerLot/CheerLot/Presentation/Roster/Views/TeamMemberListView.swift
  CheerLot/CheerLot/Presentation/Select/Views/TeamSelectView.swift
  CheerLot/CheerLot/Presentation/Song/Views/CheerSongView.swift
  CheerLot/CheerLot/Resource/Extension/Navigation+.swift
  CheerLot/CheerLot/Resource/Modifier/CustomNavigationBar.swift
Labels: ✨ Feature, 🔨 Fix, ♻️ Refactor

#102 ✨ Feat: #99 팀 멤버 리스트(라인업, 전체 선수) 새로운 api 적용
  CheerLot/.swiftlint.yml
  CheerLot/CheerLot.xcodeproj/project.pbxproj
  CheerLot/CheerLot.xcodeproj/xcshareddata/xcschemes/CheerLot.xcscheme
  CheerLot/CheerLot/Models/DTO/ResponseDto/LineupResponse.swift
  CheerLot/CheerLot/Models/Domain/CheerSong.swift
  CheerLot/CheerLot/Models/Domain/Team.swift
  CheerLot/CheerLot/Network/Core/NetworkError.swift
  CheerLot/CheerLot/Network/Core/NetworkMonitor.swift
  CheerLot/CheerLot/Network/MoyaAPI/APITargetType.swift
  CheerLot/CheerLot/Network/MoyaAPI/PlayerAPI.swift
  CheerLot/CheerLot/Network/MoyaAPI/VersionAPI.swift
  CheerLot/CheerLot/Network/Service/PlayersNetworkService.swift
  CheerLot/CheerLot/Network/Service/VersionNetworkService.swift
  CheerLot/CheerLot/Presentation/Change/Views/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Presentation/Main/ViewModels/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Presentation/Main/Views/StartingMemberListView.swift
  CheerLot/CheerLot/Presentation/Main/Views/TeamRoasterView.swift
  CheerLot/CheerLot/Presentation/Roster/Views/TeamMemberListView.swift
  CheerLot/CheerLot/Resource/Data/DataMigrationService.swift
  CheerLot/CheerLot/Service/Network/NetworkService.swift
  CheerLot/CheerLot/Service/ThemeManager.swift
  CheerLot/CheerLot/Service/WatchSessionManager.swift
Labels: ✨ Feature, 📂 Chore

#109 🔨Fix: 최근 경기 라인업 버튼 누를 시 새로고침 문제
  CheerLot/CheerLot.xcodeproj/project.pbxproj
  CheerLot/CheerLot/Presentation/Main/ViewModels/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Presentation/Main/Views/StartingMemberListView.swift
Labels: 🔨 Fix, 🚨 Hotfix

#110 🔨Fix: 전체선수 업데이트시, context에서도 기존 선수 전부 삭제
  CheerLot/CheerLot/Presentation/Main/ViewModels/TeamRoasterViewModel.swift
Labels: 🔨 Fix, 🚨 Hotfix
