Repository DeveloperAcademy-POSTECH/2025-C3-A15-AGZ, pull requests merged in 2025-07, with the labels that each got.

#75 ✨ Feat: #74 Firebase Analytics, Crashlytics 설정
  CheerLot/CheerLot.xcodeproj/project.pbxproj
  CheerLot/CheerLot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CheerLot/CheerLot.xcodeproj/xcshareddata/xcschemes/CheerLot.xcscheme
  CheerLot/CheerLot.xcodeproj/xcshareddata/xcschemes/WatchCheerLot Watch App.xcscheme
  CheerLot/CheerLot/App/CheerLotApp.swift
  CheerLot/CheerLot/GoogleService-Info.plist
  CheerLot/CheerLot/Info.plist
  CheerLot/CheerLot/Resources/Common/Components/AppInfoTextPageView.swift
  CheerLot/CheerLot/Resources/Common/Components/CheerSongMenuSheetView.swift
  CheerLot/CheerLot/Resources/Common/Components/TeamSelectSheetView.swift
  CheerLot/CheerLot/Resources/Common/Representable/SafariView.swift
  CheerLot/CheerLot/Resources/Extension/View+.swift
  CheerLot/CheerLot/Resources/Presentation/AppInfo/AboutMakerView.swift
  CheerLot/CheerLot/Resources/Presentation/AppInfo/MainAppInfoView.swift
  CheerLot/CheerLot/Resources/Presentation/ChangeMember/ChangeStartingMemberView.swift
  CheerLot/CheerLot/Resources/Presentation/CheerSong/CheerSongView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/MemberListMenuSegmentControl.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterView.swift
  CheerLot/CheerLot/Resources/Presentation/Main/TeamRoasterViewModel.swift
  CheerLot/CheerLot/Resources/Presentation/SelectTeam/TeamSelectView.swift
  CheerLot/CheerLot/Resources/Presentation/StartingMember/StartingMemberListView.swift
  CheerLot/CheerLot/Resources/Presentation/TeamMember/TeamMemberListView.swift
  CheerLot/CheerLot/Resources/Service/Manager/ThemeManager.swift
  CheerLot/CheerLot/Resources/Util/Constants.swift
  CheerLot/CheerLot/Resources/Util/Firebase/AnalyticsLogger.swift
  CheerLot/CheerLot/Resources/Util/Firebase/LoggerEvent.swift
Labels: ✨ Feature, 📂 Chore

#80 🐛 Bug: #78 선수 데이터 수정
  CheerLot/CheerLot/Sources/Data/teams.json
Labels: 🔨 Fix

#83 hotfix: 등번호 교환 이슈
  CheerLot/CheerLot/Sources/Data/teams.json
Labels: 🚨 Hotfix
